language: android
android:
  components:
    - build-tools-23.0.0
    - extra-android-m2repository
    - android-23

jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx4g"

script: ./gradlew clean build

